# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2004(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, order_id: str=None, order_status: str=None, amount_fiat: int=None, currency_id: int=None, payment_option_id: int=None, amount_sats: int=None, expires_on: datetime=None, payment_info: Dict=None):  # noqa: E501
        """InlineResponse2004 - a model defined in Swagger

        :param order_id: The order_id of this InlineResponse2004.  # noqa: E501
        :type order_id: str
        :param order_status: The order_status of this InlineResponse2004.  # noqa: E501
        :type order_status: str
        :param amount_fiat: The amount_fiat of this InlineResponse2004.  # noqa: E501
        :type amount_fiat: int
        :param currency_id: The currency_id of this InlineResponse2004.  # noqa: E501
        :type currency_id: int
        :param payment_option_id: The payment_option_id of this InlineResponse2004.  # noqa: E501
        :type payment_option_id: int
        :param amount_sats: The amount_sats of this InlineResponse2004.  # noqa: E501
        :type amount_sats: int
        :param expires_on: The expires_on of this InlineResponse2004.  # noqa: E501
        :type expires_on: datetime
        :param payment_info: The payment_info of this InlineResponse2004.  # noqa: E501
        :type payment_info: Dict
        """
        self.swagger_types = {
            'order_id': str,
            'order_status': str,
            'amount_fiat': int,
            'currency_id': int,
            'payment_option_id': int,
            'amount_sats': int,
            'expires_on': datetime,
            'payment_info': Dict
        }

        self.attribute_map = {
            'order_id': 'order_id',
            'order_status': 'order_status',
            'amount_fiat': 'amount_fiat',
            'currency_id': 'currency_id',
            'payment_option_id': 'payment_option_id',
            'amount_sats': 'amount_sats',
            'expires_on': 'expires_on',
            'payment_info': 'payment_info'
        }
        self._order_id = order_id
        self._order_status = order_status
        self._amount_fiat = amount_fiat
        self._currency_id = currency_id
        self._payment_option_id = payment_option_id
        self._amount_sats = amount_sats
        self._expires_on = expires_on
        self._payment_info = payment_info

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2004':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4 of this InlineResponse2004.  # noqa: E501
        :rtype: InlineResponse2004
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order_id(self) -> str:
        """Gets the order_id of this InlineResponse2004.


        :return: The order_id of this InlineResponse2004.
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: str):
        """Sets the order_id of this InlineResponse2004.


        :param order_id: The order_id of this InlineResponse2004.
        :type order_id: str
        """

        self._order_id = order_id

    @property
    def order_status(self) -> str:
        """Gets the order_status of this InlineResponse2004.


        :return: The order_status of this InlineResponse2004.
        :rtype: str
        """
        return self._order_status

    @order_status.setter
    def order_status(self, order_status: str):
        """Sets the order_status of this InlineResponse2004.


        :param order_status: The order_status of this InlineResponse2004.
        :type order_status: str
        """

        self._order_status = order_status

    @property
    def amount_fiat(self) -> int:
        """Gets the amount_fiat of this InlineResponse2004.


        :return: The amount_fiat of this InlineResponse2004.
        :rtype: int
        """
        return self._amount_fiat

    @amount_fiat.setter
    def amount_fiat(self, amount_fiat: int):
        """Sets the amount_fiat of this InlineResponse2004.


        :param amount_fiat: The amount_fiat of this InlineResponse2004.
        :type amount_fiat: int
        """

        self._amount_fiat = amount_fiat

    @property
    def currency_id(self) -> int:
        """Gets the currency_id of this InlineResponse2004.


        :return: The currency_id of this InlineResponse2004.
        :rtype: int
        """
        return self._currency_id

    @currency_id.setter
    def currency_id(self, currency_id: int):
        """Sets the currency_id of this InlineResponse2004.


        :param currency_id: The currency_id of this InlineResponse2004.
        :type currency_id: int
        """

        self._currency_id = currency_id

    @property
    def payment_option_id(self) -> int:
        """Gets the payment_option_id of this InlineResponse2004.


        :return: The payment_option_id of this InlineResponse2004.
        :rtype: int
        """
        return self._payment_option_id

    @payment_option_id.setter
    def payment_option_id(self, payment_option_id: int):
        """Sets the payment_option_id of this InlineResponse2004.


        :param payment_option_id: The payment_option_id of this InlineResponse2004.
        :type payment_option_id: int
        """

        self._payment_option_id = payment_option_id

    @property
    def amount_sats(self) -> int:
        """Gets the amount_sats of this InlineResponse2004.


        :return: The amount_sats of this InlineResponse2004.
        :rtype: int
        """
        return self._amount_sats

    @amount_sats.setter
    def amount_sats(self, amount_sats: int):
        """Sets the amount_sats of this InlineResponse2004.


        :param amount_sats: The amount_sats of this InlineResponse2004.
        :type amount_sats: int
        """

        self._amount_sats = amount_sats

    @property
    def expires_on(self) -> datetime:
        """Gets the expires_on of this InlineResponse2004.

        by when the payment needs to arrive for the order to be honored  # noqa: E501

        :return: The expires_on of this InlineResponse2004.
        :rtype: datetime
        """
        return self._expires_on

    @expires_on.setter
    def expires_on(self, expires_on: datetime):
        """Sets the expires_on of this InlineResponse2004.

        by when the payment needs to arrive for the order to be honored  # noqa: E501

        :param expires_on: The expires_on of this InlineResponse2004.
        :type expires_on: datetime
        """

        self._expires_on = expires_on

    @property
    def payment_info(self) -> Dict:
        """Gets the payment_info of this InlineResponse2004.


        :return: The payment_info of this InlineResponse2004.
        :rtype: Dict
        """
        return self._payment_info

    @payment_info.setter
    def payment_info(self, payment_info: Dict):
        """Sets the payment_info of this InlineResponse2004.


        :param payment_info: The payment_info of this InlineResponse2004.
        :type payment_info: Dict
        """

        self._payment_info = payment_info
