# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, supported_features: List[object]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param supported_features: The supported_features of this InlineResponse200.  # noqa: E501
        :type supported_features: List[object]
        """
        self.swagger_types = {
            'supported_features': List[object]
        }

        self.attribute_map = {
            'supported_features': 'supported_features'
        }
        self._supported_features = supported_features

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def supported_features(self) -> List[object]:
        """Gets the supported_features of this InlineResponse200.


        :return: The supported_features of this InlineResponse200.
        :rtype: List[object]
        """
        return self._supported_features

    @supported_features.setter
    def supported_features(self, supported_features: List[object]):
        """Sets the supported_features of this InlineResponse200.


        :param supported_features: The supported_features of this InlineResponse200.
        :type supported_features: List[object]
        """

        self._supported_features = supported_features
