# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2005(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, order_id: str=None, withdrawal_expiration_date: datetime=None, lnurlw: str=None):  # noqa: E501
        """InlineResponse2005 - a model defined in Swagger

        :param order_id: The order_id of this InlineResponse2005.  # noqa: E501
        :type order_id: str
        :param withdrawal_expiration_date: The withdrawal_expiration_date of this InlineResponse2005.  # noqa: E501
        :type withdrawal_expiration_date: datetime
        :param lnurlw: The lnurlw of this InlineResponse2005.  # noqa: E501
        :type lnurlw: str
        """
        self.swagger_types = {
            'order_id': str,
            'withdrawal_expiration_date': datetime,
            'lnurlw': str
        }

        self.attribute_map = {
            'order_id': 'order_id',
            'withdrawal_expiration_date': 'withdrawal_expiration_date',
            'lnurlw': 'lnurlw'
        }
        self._order_id = order_id
        self._withdrawal_expiration_date = withdrawal_expiration_date
        self._lnurlw = lnurlw

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5 of this InlineResponse2005.  # noqa: E501
        :rtype: InlineResponse2005
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order_id(self) -> str:
        """Gets the order_id of this InlineResponse2005.


        :return: The order_id of this InlineResponse2005.
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: str):
        """Sets the order_id of this InlineResponse2005.


        :param order_id: The order_id of this InlineResponse2005.
        :type order_id: str
        """

        self._order_id = order_id

    @property
    def withdrawal_expiration_date(self) -> datetime:
        """Gets the withdrawal_expiration_date of this InlineResponse2005.


        :return: The withdrawal_expiration_date of this InlineResponse2005.
        :rtype: datetime
        """
        return self._withdrawal_expiration_date

    @withdrawal_expiration_date.setter
    def withdrawal_expiration_date(self, withdrawal_expiration_date: datetime):
        """Sets the withdrawal_expiration_date of this InlineResponse2005.


        :param withdrawal_expiration_date: The withdrawal_expiration_date of this InlineResponse2005.
        :type withdrawal_expiration_date: datetime
        """

        self._withdrawal_expiration_date = withdrawal_expiration_date

    @property
    def lnurlw(self) -> str:
        """Gets the lnurlw of this InlineResponse2005.


        :return: The lnurlw of this InlineResponse2005.
        :rtype: str
        """
        return self._lnurlw

    @lnurlw.setter
    def lnurlw(self, lnurlw: str):
        """Sets the lnurlw of this InlineResponse2005.


        :param lnurlw: The lnurlw of this InlineResponse2005.
        :type lnurlw: str
        """

        self._lnurlw = lnurlw
