# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OrderstatusBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, session_id: str=None, order_id: str=None):  # noqa: E501
        """OrderstatusBody - a model defined in Swagger

        :param session_id: The session_id of this OrderstatusBody.  # noqa: E501
        :type session_id: str
        :param order_id: The order_id of this OrderstatusBody.  # noqa: E501
        :type order_id: str
        """
        self.swagger_types = {
            'session_id': str,
            'order_id': str
        }

        self.attribute_map = {
            'session_id': 'session_id',
            'order_id': 'order_id'
        }
        self._session_id = session_id
        self._order_id = order_id

    @classmethod
    def from_dict(cls, dikt) -> 'OrderstatusBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The orderstatus_body of this OrderstatusBody.  # noqa: E501
        :rtype: OrderstatusBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this OrderstatusBody.


        :return: The session_id of this OrderstatusBody.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this OrderstatusBody.


        :param session_id: The session_id of this OrderstatusBody.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def order_id(self) -> str:
        """Gets the order_id of this OrderstatusBody.


        :return: The order_id of this OrderstatusBody.
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: str):
        """Sets the order_id of this OrderstatusBody.


        :param order_id: The order_id of this OrderstatusBody.
        :type order_id: str
        """

        self._order_id = order_id
